version: '3.9'

services:
  booking-service:
    image: booking-service
    ports:
      - "8090:8090"
    build:
      context: ./booking-service
      dockerfile: ./Dockerfile
    container_name: booking-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongodb:27017
    depends_on:
      - mongodb
    networks:
      - spring

  mongodb:
      image: mongo:latest
      container_name: mongodb
      ports:
        - "27019:27017"
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=password
      volumes:
        - ./data/mongo/products:/data/db
        - .init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      networks:
        - spring
      healthcheck:
        test: [ "CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })" ]
        interval: 30s
        timeout: 10s
        retries: 5

  mongo-express:
      image: mongo-express:latest
      ports:
        - '8081:8081'
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_SERVER=mongodb
      container_name: mongo-express
      depends_on:
        - mongodb
      networks:
        - spring
volumes:
  mongo-db:
    driver: local

networks:
    spring:
      driver: bridge
